  - name: Create resource group
    azure_rm_resourcegroup:
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"
        name: "{{rg}}"
        location: "{{location}}"

  - name: Create virtual network
    azure_rm_virtualnetwork: 
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"
        resource_group: "{{rg}}"
        name: "{{vlan}}"
        address_prefixes: "{{vlanAddres}}"

  - name: Create subnet
    azure_rm_subnet: 
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"
        resource_group: "{{rg}}"
        name: "{{subnet1Name}}"
        address_prefix: "{{subnet1Addres}}"
        virtual_network: "{{vlan}}"

  - name: Create network security group that allows http and ssh
    azure_rm_securitygroup: 
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"
        resource_group: "{{rg}}"
        name: "{{secuGroupHTTP_SSH}}"
        rules:
            - name: SSH
              protocol: Tcp
              destination_port_range: 22
              access: Allow
              priority: 1001
              direction: Inbound

            - name: HTTP
              protocol: Tcp
              destination_port_range: 80
              access: Allow
              priority: 1002
              direction: Inbound

  - name: Create public dynamic ip
    azure_rm_publicipaddress: 
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"
        resource_group: "{{rg}}"
        allocation_method:  Dynamic
        name: "{{publicIpName}}"
        domain_name: "{{domainNameSrvWeb}}"

  - name: Create virtual network interface card
    azure_rm_networkinterface: 
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"
        resource_group: "{{rg}}"
        name: "{{publicInterfaceName}}"
        virtual_network: "{{vlan}}"
        subnet: "{{subnet1Name}}"
        public_ip_name: "{{publicIpName}}"
        security_group: "{{secuGroupHTTP_SSH}}"

  - name: Create VM ubuntu  on Azure
    azure_rm_virtualmachine: 
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"
        resource_group: "{{rg}}"
        name: "{{vm_os}}"
        vm_size: "{{vm_size}}"
        admin_username: "{{ linux_ssh_local_username }}"
        admin_password: "{{ linux_ssh_local_password }}"
        ssh_password_enabled: false
        ssh_public_keys: 
            - path: /home/karim/.ssh/authorized_keys
              key_data: "ssh-rsa update with your public key"
        network_interfaces: "{{publicInterfaceName}}" 
        image: 
            offer: "{{vm_offer}}"
            publisher: "{{vm_publisher}}"
            sku: "{{vm_sku}}"
            version: "{{vm_version}}"